bsm/sarama-cluster

_examples/simple.go
simple.go cannot run properly because of incompatible api.
=> fix incompatible api

balancer.go, balancer_test.go, cluster.go, cluster_test.go, cmd/sarama-cluster-cli/main.go, config.go, config_test.go, consumer.go
=> Added rebalance notification events

consumer.go
=> Rebalance in stages

balancer.go, balancer_test.go, client.go, cluster_test.go, config.go, consumer.go, partitions.go, partitions_test.go
=> Switch out sarama gopkg imports for master

consumer.go
=> Close coordinator, don't just refresh

consumer.go, partitions.go
=> Allow closing consumers even if rebalance fails

cluster_test.go
=> fix test due to sarama's change in sync_producer's config

consumer.go
ref: HighWaterMarks returns the current high water marks for each topic and partition
https://godoc.org/github.com/Shopify/sarama#Consumer
=> Add HighWaterMarks support

README.md
=> Add troubleshooting information regarding consumer not receiving messages

.travis.yml, LICENSE, Makefile, README.md, README.md.tpl, balancer_test.go, cluster_test.go, config.go, consumer.go, partitions.go, partitions_test.go
=> Commit every time, even if not dirty.

consumer.go, consumer_test.go
=> Ensure notifications are issued (and consumed) before rebalancing 

consumer.go
=> Remove delay

Gopkg.lock, Gopkg.toml, config.go, consumer.go
=> Reduce memory requirements

README.md, README.md.tpl, config.go, consumer.go, consumer_test.go, examples_test.go, partitions.go
=> Expose individual partitions

balancer.go, balancer_test.go, consumer.go, consumer_test.go
=> Adding notifications on rebalance start

.travis.yml, client.go, client_test.go, consumer.go
=> Allow to re-use clients

consumer.go
=> Make Close thread-safe

consumer.go
=> Fix race, added clarifying comment to CommitOffsets

consumer.go
Addresses https://github.com/bsm/sarama-cluster/issues/193
=> Drain channels on Close

consumer.go, consumer_test.go
=> Fix NPE on ResetOffsets and MarkOffsets

config.go
Fix a couple of typos in the comments for the code.
=> Update config.go to correct typos

consumer.go
Introduced in https://github.com/bsm/sarama-cluster/pull/271
```
go test -v .
../../bsm/sarama-cluster/consumer.go:353:54: syntax error: unexpected newline, expecting comma or )
```
=> Add missing parentheses

balancer.go, balancer_test.go, consumer.go
Issuing PR as per discussion in: https://github.com/bsm/sarama-cluster/issues/236
=> Copy Notification on error to prevent data race (#236)
