consumer.go

We had trouble when acking messages for partitions containing only a single message (which happens quite oftenly in dev). With the patch below, messages with offset 0 can be acked.

Offset 0 can be acked for partitions

---

consumer.go

The default value of RetentionTime is 0, so, offset is immediately expire.
In accordance with the DEFAULT_RETENTION_TIME of Java client, to enable the offsets.retention.minutes of Broker Config.

Use the default expiration timestamp for OffsetCommitRequest v2.

---

consumer.go

This removes the need to wait for messages to be processed, as only one message may be shifted from the 'stack' at a time. This may have an impact on performance, but it doesn't seem to be the case in my benchmarks.

Do not buffer the multiplexing messages channel

---

consumer.go

We've been getting some issues with not receiving error notifications when we hit an "Unknown Offset" error while starting a consumer.
/cc @bsm

Return error instead of returning nil

---

consumer.go

Current behavior: `consumer.rebalance()` starts with `client.RefreshMetadata()` which attempts to describe all topics. If the client only has authorization to describe specific topics, then `sarama.ErrTopicAuthorizationFailed` is returned, rebalance fails, and the `consumer.mainLoop()` starts over.
With this patch, when `sarama.ErrTopicAuthorizationFailed` is returned `consumer.rebalance()` will try calling `client.RefreshMetadata(consumer.coreTopics...)`, and the consumer will successfully subscribe to coreTopics if it has permissions for all of them.

Handle authz limited to specific topics

---

config.go
consumer.go

This implements the feature request described in #70, allowing custom `UserData` for each member to be included in the `JoinGroupRequest`.

Allow custom group member UserData to be included when joining the group

---

offsets.go
offsets_test.go

I noticed that I wasn't able to mark an offset of 0 as being processed. This change should fix that.
Note: The `MarkOffset` function in Consumer does the actual offset movement.

Fix off by one error when marking offset

---

config.go
config_test.go
consumer.go

github.com/uber/cherami-server has a use case for Sarama and Sarama-cluster where the Sarama MaxProcessingTime needs to be set to a large value. 
This conflicts with the existing use of the MaxProcessingTime in sarama-cluster in a couple of time.Sleeps(), which are used to allow time for a peer Kafka client to commit their final offsets upon loss of a partition in a rebalance. It should be noted that this style of "synchronization" is not strictly "correct", but represents a low-cost, best-effort attempt to reduce duplicate deliveries when rebalancing occurs. It is therefore acceptable that this sleep time is less than the actual MaxProcessingTime. We can have a detailed discussion of the (lack of) consequences to this, if desired. 
This PR proposes to add a new parameter to …

Allow configurable offset synchronization sleep duration

---

cluster.go
consumer.go
partitions.go
util.go

Force rebalance when partition consumers exit with an error

---

Makefile

Travis tests for 0.9.0.1 is broken on the master. This is due bad kafka mirror.
This might fix the issue.

Fix the kafka source - 0.9.0.1 testing broken

---

cluster_test.go
consumer.go
consumer_test.go
offsets.go
offsets_test.go
partitions.go
partitions_test.go

This commit is in alignment with the sarama library commits to reset offsets
https://github.com/Shopify/sarama/commit/b966238f31778386bce80c28a12fde729e01cab4#diff-3ca6d659defd100fe2de43adf2b8f41e
https://github.com/Shopify/sarama/commit/96fa1c837819761fc5c706010a9677aab15ca46d#diff-3ca6d659defd100fe2de43adf2b8f41e

Allow marking of earlier offsets

---

consumer_test.go
partitions.go

Fix for #205. The only bit I am unsure of is the fact that `Errors()` is now exposed on the `PartitionConsumer` while being also multiplexed into one big errors channel. I am a little tempted to remove the multiplexing for `Errors` as well.

Unify PartitionConsumer interface

---

balancer.go
consumer.go
partitions.go
partitions_test.go

Expose offset methods on partition consumers

---

partitions.go

Sometimes we need to know the initial offset of a PartitionConsumer

add Offset() to PartitionConsumer interface

---

consumer.go
partitions.go

Sarama-cluster calls Sarama [Close](https://github.com/Shopify/sarama/blob/master/consumer.go#L281) on [Consumer.Close](https://github.com/bsm/sarama-cluster/blob/master/consumer.go#L298) and [PartitionConsumer.AsyncClose](https://github.com/bsm/sarama-cluster/blob/master/partitions.go#L89). 
When using the sarama-consumer `PartitionConsumer` abstraction, this may result in dataloss, because on rebalance or consumer shutdown, consumer application and sarama will both read from the same `Messages` channel which will result in the application receiving message stream with holes (e.g., offset 100, 102, 104, etc). Since `PartitionConsumer` application is not synchronously notified of rebalance, this diff changes sarama cluster to use `AsyncClose` to prevent this dual drain race condition.

Fix PartitionConsumer race condition on Close.

---

consumer.go
partitions.go

While chaos testing some code that uses sarama-consumer in `PartitionModeConsumer`, we happened upon an area where the functionality doesn't correspond to the documentation.  We were listening on the `Errors()` channel on the `PartitionConsumer` as documented, but we found that there was a race where some of the errors were surfacing on the Consumer's error channel and the rest on the partition consumer's.  This patch brings the functionality in line with the docs by removing the loop in the consumer that drains/muxes the partition consumer's errors.  Thanks!

made error handling in PartitionModeConsumer conform to docs

---

consumer.go

Howdy, upstream contributors!
We have been using this awesome repo. I ran into a race condition yesterday in a test. Looked into it a bit and found that the notification was passed through the channel as a pointer and the creator modifies it after. This causes a race with the reader.
Made an one line change and would love to hear what you think! :)

Fixed race condition when changing a notification after sending

---

balancer.go
balancer_test.go
consumer.go

The CG coordinator chooses a group protocol by inspecting the
ordered protocols in the JoinGroup requests and choosing one that
all members support.  The CG leader is expected to use this choice
to assign partitions.  Currently, though, the protocol on the CG
leader is read from config.  This isn't an issue if all consumers
are using sarama, but if consumers are using mixed libraries, then
it could result in the sarama CG leader choosing a protocol that
is not supported by other consumers.

Use GroupProtocol chosen by CG Coordinator

---

consumer.go
consumer_test.go

We have seamless deploy. When new service is deployed a rebalance begins (at that moment we have the old service and the new one). While rebalance is going on the old service is shutting down and deadlock occurs.

fix dying consumer deadlock during rebalance

---

consumer.go

Hi, we updated an exported function comment based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

consumer.go

This patch fixes small typo in godoc.

Fix typo in godoc
